
/**
 * DO NOT MODIFY this file manually, this file is generated by 'yarn generateCode',
 * just write your plugin or launcher and run 'yarn generateCode',
 * this file will be updated automatically.
 */

import { IPlugin } from '../common';
import sspaiPlugin from './sspai';

const plugins: IPlugin[] = [sspaiPlugin];

export default plugins;
