
/**
 * DO NOT MODIFY this file manually, this file is generated by 'yarn generateCode',
 * just write your plugin or launcher and run 'yarn generateCode',
 * this file will be updated automatically.
 */

import { ILauncher } from '../common';
import obsidianLauncher from './obsidian';

const launchers: ILauncher<string>[] = [obsidianLauncher as ILauncher<string>];

export default launchers;
